/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cmdApiKeys;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;

public class AppTest {

    @Test
    public void testAppHasSecondGreeting() throws URISyntaxException, IOException, InterruptedException {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getApiKeys("https://dev-portal.fs.gsa.gov/dev/mtwform"));
    }

    @Test
    public void testConnectAndParse() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.connectAndParse("https://dev-portal.fs.gsa.gov/dev/mtwform"));
    }

    @Test
    public void testWriteKeyOutput() throws IOException {
        App classUnderTest = new App();
        String outputContent = "This is the content that should be output";
        String outputFilename = "outputFileTest.txt";
        classUnderTest.writeKeyOutput(outputContent, outputFilename);
        File file = new File(outputFilename);
        assertTrue(file.exists());
        String fileContent = readFile(outputFilename, StandardCharsets.US_ASCII);
        assertEquals(fileContent, outputContent);
        
    }

    static String readFile(String path, Charset encoding)
    throws IOException
    {
    byte[] encoded = Files.readAllBytes(Paths.get(path));
    return new String(encoded, encoding);
    }
}
