/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gov.gsa.faas.tools.formdeployer.type;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class SingleAccess {

    private List<String> roles = new ArrayList<>();
    private String type;

    public SingleAccess() {
    }

    public SingleAccess(List<String> roles, String type) {
        this.roles = roles;
        this.type = type;
    }

    public List<String> getRoles() {
        return this.roles;
    }

    public void setRoles(List<String> roles) {
        this.roles = roles;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof SingleAccess)) {
            return false;
        }
        SingleAccess singleAccess = (SingleAccess) o;
        return Objects.equals(roles, singleAccess.roles) && Objects.equals(type, singleAccess.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(roles, type);
    }

    @Override
    public String toString() {
        return "{" +
            " roles='" + getRoles() + "'" +
            ", type='" + getType() + "'" +
            "}";
    }
    
}
